#! /usr/bin/bash
#SBATCH --job-name=Credit_hyper
#SBATCH --partition=pe2
#SBATCH --mail-type=ALL
#SBATCH --mail-user=aelhussein@nygenome.org
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=15G
#SBATCH --time=40:00:00

source ~/anaconda3/bin/activate
conda activate torch_env

DIR='/gpfs/commons/groups/gursoy_lab/aelhussein/ot_cost/otcost_fl_rebase'
DATASET='Credit'
python $DIR/code/run_models/run.py --dataset=$DATASET --hyperparameter=True
