#! /usr/bin/bash
#SBATCH --job-name=ISIC_hyper
#SBATCH --partition=gpu
#SBATCH --mail-type=ALL
#SBATCH --mail-user=aelhussein@nygenome.org
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=10G
#SBATCH --gres=gpu:1
#SBATCH --time=25:00:00

source ~/anaconda3/bin/activate ~/anaconda3/envs/cuda_env/
conda activate cuda_env
module load cuda

DIR='/gpfs/commons/groups/gursoy_lab/aelhussein/ot_cost/otcost_fl_rebase'
DATASET='ISIC'
python $DIR/code/run_models/run.py --dataset=$DATASET --hyperparameter=True